# -*- coding: utf-8 -*-
"""face-detection-engl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18r-HGlL1Iw5LACdCAj8xsPh7ah7bgwUr
"""

import os
import random
from PIL import Image
import matplotlib.pyplot as plt

DATA_DIR = "/kaggle/input/scface/SCface_database"

all_images = []

for root, dirs, files in os.walk(DATA_DIR):
    for f in files:
        if f.lower().endswith(('.jpg', '.png', '.jpeg')):
            all_images.append(os.path.join(root, f))

print("num-of-img:", len(all_images))

sample = random.sample(all_images, 9)
plt.figure(figsize=(10,10))

for i, path in enumerate(sample):
    img = Image.open(path)
    plt.subplot(3,3,i+1)
    plt.imshow(img)
    plt.axis("off")

plt.show()

"""> STEP 1: Build raw SCFACE table (df_full) from all folders"""

import os
import pandas as pd


data_list = []

for root, dirs, files in os.walk(DATA_DIR):
    for f in files:
        if f.lower().endswith(('.jpg', '.jpeg', '.png', '.ppm')):
            image_path = os.path.join(root, f)
            person_id = os.path.basename(root)

            if "mugshot" in root.lower():
                img_type = "Mugshot"
                distance = "Mugshot"
                camera = "Mugshot"
            elif "surveillance_cameras_distance_1" in root.lower():
                img_type = "Surveillance"
                distance = "1m"
                camera = os.path.basename(root)
            elif "surveillance_cameras_distance_2" in root.lower():
                img_type = "Surveillance"
                distance = "2m"
                camera = os.path.basename(root)
            elif "surveillance_cameras_distance_3" in root.lower():
                img_type = "Surveillance"
                distance = "3m"
                camera = os.path.basename(root)
            elif "IR" in root.lower():
                img_type = "IR"
                distance = "IR"
                camera = "IR_cam8"
            else:
                img_type = "Unknown"
                distance = "Unknown"
                camera = "Unknown"

            data_list.append([image_path, person_id, camera, distance, img_type])

df = pd.DataFrame(data_list, columns=["image_path","person_id","camera","distance","type"])
df.head()

df.loc[df['image_path'].str.contains("surveillance_cameras_IR_cam8", case=False), 'type'] = "IR"
df.loc[df['image_path'].str.contains("surveillance_cameras_IR_cam8", case=False), 'distance'] = "IR"
df.loc[df['image_path'].str.contains("surveillance_cameras_IR_cam8", case=False), 'camera'] = "IR_cam8"


print(df['type'].value_counts())
print(df['distance'].value_counts())

print("\n img-num of distance:")
print(df['distance'].value_counts())

print("\n img-num of camera:")
print(df['camera'].value_counts())

import matplotlib.pyplot as plt
from PIL import Image
import random

def show_samples_by_type(img_type):
    paths = df[df['type']==img_type]['image_path'].tolist()
    sample = random.sample(paths, min(9, len(paths)))

    plt.figure(figsize=(10,10))
    for i, p in enumerate(sample):
        img = Image.open(p)
        plt.subplot(3,3,i+1)
        plt.imshow(img)
        plt.axis("off")
    plt.suptitle(f"Samples from {img_type}", fontsize=18)
    plt.show()

show_samples_by_type("Mugshot")
show_samples_by_type("Surveillance")
show_samples_by_type("IR")

def show_samples(distance_path, title_text):
    paths = []

    for root, dirs, files in os.walk(distance_path):
        for f in files:
            if f.lower().endswith(('.jpg', '.jpeg', '.png', '.ppm')):
                paths.append(os.path.join(root, f))

    print(f"{title_text} → عدد الصور:", len(paths))

    sample = random.sample(paths, 9)

    plt.figure(figsize=(10,10))
    for i, p in enumerate(sample):
        img = Image.open(p)
        plt.subplot(3,3,i+1)
        plt.imshow(img)
        plt.axis("off")

    plt.suptitle(title_text, fontsize=18)
    plt.show()


show_samples(DATA_DIR + "/surveillance_cameras_distance_1", "Distance = 1m")
show_samples(DATA_DIR + "/surveillance_cameras_distance_2", "Distance = 2m")
show_samples(DATA_DIR + "/surveillance_cameras_distance_3", "Distance = 3m")

"""# EDA -Milestone1

> Preliminary exploratory data analysis
"""

import pandas as pd

records = []

for path in all_images:
    filename = path.split("/")[-1]
    folder = path.split("/")[-2]     # camera or mugshot folder

    # استخراج person_id حسب شكل الاسم
    # مثال "001_01_1.jpg" → الشخص 001
    pid = filename.split("_")[0].zfill(3)

    # تحديد النوع (mugshot / visible / IR)
    if "mugshot" in path.lower():
        img_type = "mugshot"
    elif "IR" in path or "ir" in path.lower():
        img_type = "infrared"
    else:
        img_type = "visible_surveillance"

    records.append({
        "image_path": path,
        "person_id": pid,
        "folder": folder,
        "type": img_type
    })

df_raw = pd.DataFrame(records)
df_raw.head()

"""### ETL Workflow – Data Integration

To build a unified view of the SCFACE dataset, We:

1. Traversed all folders under the SCFACE root directory, including:
   - **surveillance_cameras_distance_1/2/3**
   - **surveillance_cameras_all**
   - **mugshot_frontal_**
   - **mugshot_rotation_all**
   - **surveillance_cameras_IR_cam8**
2. For each image file, We extracted:
   - **image_path** (full file path)
   - **person_id** (subject ID parsed from the filename)
   - **folder** (the immediate parent folder)
   - High-level metadata: **type**, **distance**  **camera**.
3. Combined all image records into a single dataframe `df_raw`, where **each row corresponds to one image**.

"""

import re

def infer_distance_and_camera(row):
    path = row["image_path"].lower()
    folder = row["folder"].lower()

    # Default values
    distance = "Unknown"
    camera = "Unknown"

    # Surveillance distances
    if "surveillance_cameras_distance_1" in path:
        distance = "1m"
    elif "surveillance_cameras_distance_2" in path:
        distance = "2m"
    elif "surveillance_cameras_distance_3" in path:
        distance = "3m"

    # Camera id (cam_1 .. cam_7)
    cam_match = re.search(r"cam[_\-]?(\d+)", path)
    if cam_match:
        camera = f"cam_{cam_match.group(1)}"

    # Mugshot
    if "mugshot" in folder:
        distance = "Mugshot"
        camera = "Mugshot"

    # IR
    if "surveillance_cameras_ir_cam8" in folder:
        distance = "IR"
        camera = "IR_cam8"

    return pd.Series({"distance": distance, "camera": camera})

meta = df_raw.apply(infer_distance_and_camera, axis=1)
df_raw = df_raw.drop(columns=['distance', 'camera'], errors='ignore')
df_raw = pd.concat([df_raw, meta], axis=1)

# --- Basic statistics and dataset overview ---

print("Total images:", len(df_raw))
print("Unique persons:", df_raw['person_id'].nunique())

print("\nImage count per type:")
print(df_raw['type'].value_counts())

print("\nImage count per distance:")
print(df_raw['distance'].value_counts())

print("\nImage count per camera:")
print(df_raw['camera'].value_counts())

# Optional: describe distribution of images per person
person_counts = df_raw['person_id'].value_counts()

print("\n--- Images per person (summary statistics) ---")
print(person_counts.describe())

# --- Check for missing values in df_raw ---

print("Missing values per column:")
print(df_raw.isnull().sum())

total_missing = df_raw.isnull().sum().sum()
print("\nTotal missing values in the dataset:", total_missing)

if total_missing == 0:
    print("\n No missing values detected.")
else:
    print("\n Missing values found. Consider cleaning or removing affected rows.")

# --- Check for duplicate rows ---

duplicate_count = df_raw.duplicated().sum()
print("Number of duplicate rows:", duplicate_count)

if duplicate_count > 0:
    print("\n Duplicates found. Removing duplicates...")
    df_raw = df_raw.drop_duplicates()
    print("Duplicates removed. New dataset size:", len(df_raw))
else:
    print("\n No duplicate rows found.")

"""* Visualizations
* Correlations
*  Trends
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
import textwrap

# -------------------------------------
# Function to add labels above bars
def add_labels(ax):
    for p in ax.patches:
        value = int(p.get_height())
        ax.text(
            p.get_x() + p.get_width()/2,
            p.get_height(),
            value,
            ha='center', va='bottom',
            fontsize=10, color="#1B4F72", fontweight='bold'
        )

# -------------------------------------

c1 = "#1B4F72"   # Blue (primary)
c2 = "#117864"   # Teal
c3 = "#7B241C"   # Academic Burgundy
c4 = "#B7950B"   # Muted Gold
c5 = "#5D6D7E"   # Cool Gray

plt.figure(figsize=(22, 16))

# -------------------------------------------------------
plt.subplot(3, 3, 1)
ax1 = df_raw['type'].value_counts().plot(kind='bar', color=[c1, c2, c3, c4])
plt.title("Distribution by Image Type")
plt.xticks(rotation=45)
add_labels(ax1)

# -------------------------------------------------------
plt.subplot(3, 3, 2)
ax2 = df_raw['distance'].value_counts().plot(kind='bar', color=c2)
plt.title("Images per Distance Category")
plt.xticks(rotation=45)
add_labels(ax2)

# -------------------------------------------------------
plt.subplot(3, 3, 3)
ax3 = df_raw['camera'].value_counts().plot(kind='bar', color=c1)
plt.title("Images per Camera")
plt.xticks(rotation=45)
add_labels(ax3)

# -------------------------------------------------------
# Histogram fix
plt.subplot(3, 3, 4)

counts = df_raw['person_id'].value_counts()
n, bins, patches = plt.hist(counts, bins=15, color=c3)

plt.title("Distribution of Images per Person")
plt.xlabel("Images per Person")
plt.ylabel("Frequency")

if len(n) == 1:
    plt.text(
        bins[0] + (bins[1] - bins[0]) / 2,
        n[0],
        str(int(n[0])),
        ha='center',
        va='bottom',
        fontsize=12,
        fontweight='bold',
        color=c1
    )

# -------------------------------------------------------
plt.subplot(3, 3, 5)
heatmap_data = df_raw.groupby(['type', 'distance']).size().unstack(fill_value=0)
sns.heatmap(heatmap_data, annot=True, fmt='d', cmap='Blues', cbar=False)
plt.title("Type vs Distance Relationship")

# -------------------------------------------------------
plt.subplot(3, 3, 6)
folder_counts = df_raw['folder'].value_counts()

ax6 = plt.barh(folder_counts.index, folder_counts.values, color=c4)
plt.title("Image Count per Folder")
plt.xlabel("Count")

add_labels_h(plt.gca(), folder_counts.values)

plt.xticks(rotation=0)
plt.yticks(rotation=0)

# -------------------------------------------------------
# PIE CHART
plt.subplot(3, 3, 7)

pie_counts = df_raw['type'].value_counts()
labels = pie_counts.index
colors = [c1, c2, c3, c4]

patches, texts, autotexts = plt.pie(
    pie_counts,
    autopct='%1.1f%%',
    startangle=90,
    colors=colors,
    textprops={'color': 'white', 'fontsize': 11}
)

for a in autotexts:
    a.set_fontsize(12)
    a.set_weight('bold')

plt.title("Image Type Percentage")
plt.ylabel("")

plt.legend(
    patches, labels,
    title="Image Types",
    loc="center left",
    bbox_to_anchor=(1.05, 0.5),
    fontsize=12,
    title_fontsize=12
)

plt.xticks(rotation=0)
plt.yticks(rotation=0)

plt.tight_layout()
plt.show()

"""### Tools and Technologies

- **Environment:** Kaggle Notebook
- **Programming language:** Python
- **Data source:** SCFACE face recognition dataset from (Kaggle)
- **ETL and data processing:**
  - "os" for file system traversal and folder inspection
  - "pandas" for building tabular datasets (df_raw) and data cleaning
  - "numpy" for basic numerical operations
- **Image handling:**
  - "PIL" for loading and converting images
- **Visualization:**
  - "'matplotlib" and "seaborn" for plots, bar charts, histograms, and heatmaps

"""

import json

schema_m1 = {
    "project": "SCFace - Face Recognition in Surveillance Conditions",
    "table_name": "df_raw",
    "num_rows": int(len(df_raw)),
    "num_columns": df_raw.shape[1],
    "columns": {
        "image_path": {
            "type": "string",
            "description": "Full file path to the original image."
        },
        "person_id": {
            "type": "categorical",
            "description": "Subject ID extracted from filename (001–130)."
        },
        "folder": {
            "type": "string",
            "description": "The directory where the image was found (e.g., cam_1, mugshot_rotation_all)."
        },
        "type": {
            "type": "categorical",
            "description": "High-level category: visible_surveillance, mugshot, infrared, or augmented."
        },
        "distance": {
            "type": "categorical",
            "description": "1m, 2m, 3m, Mugshot, IR, or Unknown (for augmented images)."
        },
        "camera": {
            "type": "categorical",
            "description": "Camera identifier: cam_1–cam_7, IR_cam8, Mugshot, or Unknown."
        }
    },
    "entities": {
        "Person": {
            "primary_key": "person_id",
            "description": "Represents one of the 130 subjects in SCFACE."
        },
        "Image": {
            "primary_key": "image_path",
            "description": "Each row corresponds to a single image."
        }
    },
    "relationships": [
        "Person (1) --- (N) Image  via person_id"
    ]
}

with open("Milestone1_Data_Schema.json", "w") as f:
    json.dump(schema_m1, f, indent=4)

print("Saved Milestone1_Data_Schema.json")

"""### Entity–Relationship Documentation

The dataset contains one main table (df_raw) containing all SCFACE images.  
Two conceptual entities exist:

---

#### **Entity 1 — Person**
- Primary key: `person_id`
- Description: Each of the 130 subjects in SCFACE.

#### **Entity 2 — Image**
- Primary key: `image_path`
- Attributes: `folder`, `type`, `distance`, `camera`
- Description: Each row corresponds to one face image (mugshot, surveillance, IR, or augmented).

---

### **Relationship**
There is a **one-to-many** relationship between Person and Image:

# Milestone2
"""

import os

PROCESSED_DIR = "./processed_scface_images"
os.makedirs(PROCESSED_DIR, exist_ok=True)

IMG_SIZE = 224  # Standard size for ML models

"""> Resize → Convert to RGB → Save

  
*  Loads an image, converts it to RGB, resizes it to a fixed dimension,    and returns the processed PIL image.    *

"""

from PIL import Image

def process_image(path, img_size=IMG_SIZE):
    img = Image.open(path)
    img = img.convert("RGB")
    img = img.resize((img_size, img_size))
    return img

processed_records = []

for idx, row in df_raw.iterrows():
    raw_path = row["image_path"]
    person_id = row["person_id"]

    try:
        img_proc = process_image(raw_path)

        new_filename = f"person{person_id}_img{idx:05d}.jpg"
        new_path = os.path.join(PROCESSED_DIR, new_filename)

        img_proc.save(new_path)

        processed_records.append({
            "person_id": person_id,
            "raw_path": raw_path,
            "processed_path": new_path,
            "type": row["type"],
            "distance": row["distance"],
            "camera": row["camera"],
        })

    except Exception as e:
        print("Error processing:", raw_path, e)

df_processed = pd.DataFrame(processed_records)
df_processed.head()

"""# Feature Engineering (brightness + blur)"""

import numpy as np
import cv2

brightness_values = []
blur_values = []
contrast_values = []

for p in df_processed["processed_path"]:
    img = Image.open(p).convert("L")
    img_np = np.array(img)

    # Brightness = average pixel value
    brightness_values.append(img_np.mean())

    # Blur = variance of Laplacian
    blur_values.append(cv2.Laplacian(img_np, cv2.CV_64F).var())
    # contrast
    contrast_values.append(img_np.std())

df_processed["brightness"] = brightness_values
df_processed["blur"] = blur_values
df_processed["contrast"] = contrast_values

print("Processed image size check:")
sizes = set()

for p in df_processed["processed_path"]:
    img = Image.open(p)
    sizes.add(img.size)

print(sizes)

print(df_processed.isnull().sum())

print("Unique persons:", df_processed['person_id'].nunique())
print("Total processed images:", len(df_processed))
print("Total raw images:", len(df_raw))

df_processed.to_csv("SCFACE_processed_metadata.csv", index=False)
print("Saved processed metadata file.")



"""### Data Lineage and Metadata Documentation


1. **Raw input (df_raw):**
   - Contains all original and augmented image paths.
   - Includes metadata: type, distance, camera, folder, and person_id.

2. **Image transformation:**
   - All images converted to RGB format.
   - Uniform resizing to 224 × 224 pixels.
   - Saved into a structured directory

3. **Processed output (df_processed):**
   - Contains paths to both raw and processed images.
   - Inherits metadata from df_raw.
   - Adds engineered features:
     - `brightness`: average grayscale intensity
     - `blur`: Laplacian variance (image sharpness)

4. **Validation checks:**
   - Verified identical image count between raw and processed datasets.
   - Ensured consistent image dimensions.
   - Confirmed no missing values after processing.

# Show images before Processed and after
"""

import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
import cv2

row = df_processed.iloc[0]

raw_img = Image.open(row["raw_path"])
proc_img = Image.open(row["processed_path"])

plt.figure(figsize=(10,4))

plt.subplot(1, 2, 1)
plt.imshow(raw_img)
plt.title("Original Image")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(proc_img)
plt.title("Processed Image (Resized)")
plt.axis("off")

plt.show()

row = df_processed.sample(1).iloc[0]


img = Image.open(row["processed_path"]).convert("L")
img_np = np.array(img)


laplacian = cv2.Laplacian(img_np, cv2.CV_64F)

plt.figure(figsize=(10,4))

# الصورة قبل
plt.subplot(1, 2, 1)
plt.imshow(img_np, cmap='gray')
plt.title("Processed Image (Before Blur Detection)")
plt.axis("off")

# الصورة بعد
plt.subplot(1, 2, 2)
plt.imshow(np.absolute(laplacian), cmap='gray')
plt.title("Laplacian Filter Output (Blur Detection)")
plt.axis("off")

plt.show()

row = df_processed.sample(1).iloc[0]

img_rgb = Image.open(row["processed_path"]).convert("RGB")

img_gray = Image.open(row["processed_path"]).convert("L")
img_gray_np = np.array(img_gray)

brightness_value = img_gray_np.mean()

plt.figure(figsize=(12,4))


plt.subplot(1, 3, 1)
plt.imshow(img_rgb)
plt.title("Processed Image (RGB)")
plt.axis("off")

#  grayscale
plt.subplot(1, 3, 2)
plt.imshow(img_gray_np, cmap="gray")
plt.title("Grayscale Image")
plt.axis("off")

#  brightness
plt.subplot(1, 3, 3)
plt.text(0.1, 0.5, f"Brightness Value:\n{brightness_value:.2f}",
         fontsize=18)
plt.axis("off")

plt.show()

print("Brightness value (saved in df):", row["brightness"])

import numpy as np
import matplotlib.pyplot as plt
from PIL import Image, ImageEnhance

row = df_processed.sample(1).iloc[0]

img_rgb = Image.open(row["processed_path"]).convert("RGB")

img_gray = Image.open(row["processed_path"]).convert("L")
img_gray_np = np.array(img_gray)

enhancer = ImageEnhance.Contrast(img_gray)
img_contrast_enhanced = enhancer.enhance(2.0)  # تضخيم التباين ×2

contrast_value = row["contrast"]

plt.figure(figsize=(14, 4))

# original img
plt.subplot(1, 4, 1)
plt.imshow(img_rgb)
plt.title("Processed Image (RGB)")
plt.axis("off")

# grayscale img
plt.subplot(1, 4, 2)
plt.imshow(img_gray_np, cmap="gray")
plt.title("Grayscale Image")
plt.axis("off")

# contrast img
plt.subplot(1, 4, 3)
plt.imshow(img_contrast_enhanced, cmap="gray")
plt.title("Contrast Enhanced (x2)")
plt.axis("off")


plt.subplot(1, 4, 4)
plt.text(0.2, 0.5, f"Contrast Value:\n{contrast_value:.2f}", fontsize=18)
plt.axis("off")

plt.show()

print("Contrast value (saved in df):", contrast_value)

"""# Done"""